; PlatformIO Project Configuration File

[base]
platform = espressif32@6.3.2
board = m5stack-core2
framework = arduino

[env:m5stack-core2]
extends = base
build_src_filter = +<main.cpp>
lib_ldf_mode = deep+
lib_deps =
    m5stack/M5Unified@^0.2.13
    m5stack/M5GFX
    h2zero/NimBLE-Arduino@^2.4.0
    adafruit/Adafruit seesaw Library@^1.7.9