; PlatformIO Project Configuration File

[base]
platform = espressif32@6.3.2
board = m5stack-core2
framework = arduino
monitor_speed = 115200

[env:m5stack-core2-host]
extends = base
build_src_filter = +<main.cpp>
build_flags =
    -DBLE_FORCE_ROLE_HOST=1
lib_ldf_mode = deep+
lib_deps =
    m5stack/M5Unified@^0.2.13
    m5stack/M5GFX
    h2zero/NimBLE-Arduino@^2.4.0
    adafruit/Adafruit seesaw Library@^1.7.9
    hideakitai/Tween@^0.4.2

[env:m5stack-core2-client]
extends = base
build_src_filter = +<main.cpp>
build_flags =
    -DBLE_FORCE_ROLE_CLIENT=1
lib_ldf_mode = deep+
lib_deps =
    m5stack/M5Unified@^0.2.13
    m5stack/M5GFX
    h2zero/NimBLE-Arduino@^2.4.0
    adafruit/Adafruit seesaw Library@^1.7.9
    hideakitai/Tween@^0.4.2

[env:m5stack-core2]
extends = base
build_src_filter = +<main.cpp>
lib_ldf_mode = deep+
lib_deps =
    m5stack/M5Unified@^0.2.13
    m5stack/M5GFX
    h2zero/NimBLE-Arduino@^2.4.0
    adafruit/Adafruit seesaw Library@^1.7.9
    hideakitai/Tween@^0.4.2
